### ISSUE TITLE
Swift 1.2 compilation

### ISSUE THREAD

**Issue by timsp8** [Ahmed-Ali/RealmObjectEditor#4]
Has anyone successfully got this project compiling in Swift 1.2?

The protocol func 'attributeTypeDidChange:' seems to be moaning about being over @objc overloaded.

"Compiler error: Method with Objective-C selector conflicts with previous declaration with the same Objective-C selector"

**Comment by Ahmed-Ali** [comment]
Unfortunately, I have not updated the project for the latest xCode and Swift updates.
I will try to give it a look as soon as possible.

**Comment by mextex** [comment]
Looks great! Are you still planning an update to the latest xCode and Swift versions?

**Comment by Ahmed-Ali** [comment]
Done now. Thanks for the reminded.
